# Generated by Django 3.2.4 on 2022-11-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
