# Generated by Django 3.2.4 on 2022-11-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DH_App', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
