# Generated by Django 3.2.4 on 2022-11-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_App', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
