# Generated by Django 3.2.4 on 2022-11-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_App', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
